/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alura.storedina.view;

import com.alura.storedina.controller.FrmTiendaController;
import com.alura.storedina.models.Client;
import com.alura.storedina.models.Order;
import com.alura.storedina.models.Product;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class FrmTiendaDina extends javax.swing.JFrame {

    /**
     * Creates new form FrmTiendaDina
     */        
    
    private FrmTiendaController frmTiendaController = new FrmTiendaController();
    private int amount = 1;
    private String clientName;
    private String clientDni;
    
    public FrmTiendaDina(String clientName, String clientDni) {
        initComponents();
        startComponents();
        
        this.clientName = clientName;        
        this.clientDni = clientDni;
    }

    private FrmTiendaDina() {        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAmount = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProducts = new javax.swing.JTable();
        btAddProduct = new javax.swing.JButton();
        btRemoveProduct = new javax.swing.JButton();
        btBuy = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Tienda Dina");

        jLabel2.setText("Product:");

        cbAmount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        cbAmount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAmountItemStateChanged(evt);
            }
        });
        cbAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAmountActionPerformed(evt);
            }
        });

        jLabel3.setText("Amount:");

        cbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Elige tu producto--" }));
        cbProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductActionPerformed(evt);
            }
        });

        jLabel4.setText("Price:");

        txtPrice.setText("0.00");
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        tbProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Amount", "Unitary Price", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProducts.setRowHeight(30);
        jScrollPane2.setViewportView(tbProducts);

        btAddProduct.setText("Add Product");
        btAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddProductMouseClicked(evt);
            }
        });
        btAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProductActionPerformed(evt);
            }
        });

        btRemoveProduct.setText("Remove Product");
        btRemoveProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoveProductMouseClicked(evt);
            }
        });
        btRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveProductActionPerformed(evt);
            }
        });
        btRemoveProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btRemoveProductKeyPressed(evt);
            }
        });

        btBuy.setText("Buy");
        btBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRemoveProduct)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbAmount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(120, 120, 120)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btAddProduct)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btBuy)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel1))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddProduct))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRemoveProduct)
                    .addComponent(btBuy))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startComponents() {
        //We load combo box Products and Amount 
        frmTiendaController.loadComboProduct(cbProduct);                      
    }
    
    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemoveProductActionPerformed

    private void btAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProductActionPerformed
       
    }//GEN-LAST:event_btAddProductActionPerformed

    private void cbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductActionPerformed
        if(cbProduct.getSelectedIndex() != 0) {
            
            //We get to the index of product
            Product product = (Product) cbProduct.getSelectedItem();
            
            //We load combo box amount
            frmTiendaController.loadComboAmount(cbAmount, product);                     

            //We update txtPrice where is select a product in cbProduct
            frmTiendaController.updateTxtPrice(txtPrice, product, 1);
        }
    }//GEN-LAST:event_cbProductActionPerformed

    private void cbAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAmountActionPerformed
        if(cbAmount.getItemCount() > 1 && cbProduct.getSelectedIndex() != 0) {
            amount = (int) cbAmount.getSelectedItem();                          
            Product product = (Product) cbProduct.getSelectedItem();
            
            //We update TextPrice where is selected cbAmount
            frmTiendaController.updateTxtPrice(txtPrice, product, amount);
        }        
    }//GEN-LAST:event_cbAmountActionPerformed

    private void cbAmountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAmountItemStateChanged
        
    }//GEN-LAST:event_cbAmountItemStateChanged

    private void btAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddProductMouseClicked
        
        if(cbProduct.getSelectedIndex() != 0) {
            Product product = (Product) cbProduct.getSelectedItem();
            int amount  = (int) cbAmount.getSelectedItem();
            BigDecimal totalPrice = new BigDecimal(txtPrice.getText());
            int index  = (int) cbProduct.getSelectedIndex();
            
            //We add the date of product in the table(JFrame)
            frmTiendaController.addItemInTable(tbProducts, product, amount, index, totalPrice);                                    
        }
        else {
            //We show message
            JOptionPane.showMessageDialog(null, "Selected your product first.");
        }
    }//GEN-LAST:event_btAddProductMouseClicked

    private void btBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuyMouseClicked
                        
        if(tbProducts.getRowCount() > 0) {            
            frmTiendaController.addItemToDataBase(tbProducts, clientName, clientDni);     

            //We erase the data of the table
            DefaultTableModel model = (DefaultTableModel) tbProducts.getModel();
            model.setRowCount(0);

            //We show the message
            JOptionPane.showMessageDialog(null, "Compra realizada correctamente.");
        }
        else {
            JOptionPane.showMessageDialog(null, "You don't have none product in your list.");
        }
    }//GEN-LAST:event_btBuyMouseClicked

    private void btRemoveProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btRemoveProductKeyPressed
        
       
    }//GEN-LAST:event_btRemoveProductKeyPressed

    private void btRemoveProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoveProductMouseClicked
       
        if(tbProducts.getSelectedRow() != -1) {
            //We remove products with controller
            frmTiendaController.removeProductAtTable(tbProducts);
            //We show the message
            JOptionPane.showMessageDialog(null, "Product remove sucessful");
        }
        else {
            //We show the message
            JOptionPane.showMessageDialog(null, "For remove select a product in the table.");
        }                
    }//GEN-LAST:event_btRemoveProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTiendaDina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTiendaDina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTiendaDina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTiendaDina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTiendaDina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddProduct;
    private javax.swing.JButton btBuy;
    private javax.swing.JButton btRemoveProduct;
    private javax.swing.JComboBox<String> cbAmount;
    private javax.swing.JComboBox<String> cbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbProducts;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
